<a href="https://colab.research.google.com/github/pavannaik321/Digit-Recognition/blob/main/HandWrittienDigitRecognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##import Libraries

In [47]:
#Handwritten Digit Recognition using LeNet-5 CNN Architecture on MNIST Digit Database
import numpy as np
import pandas as pd

In [48]:
from tensorflow.keras import datasets

In [49]:
(x_train , y_train) , (x_test , y_test) = datasets.mnist.load_data()

In [50]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [51]:

#the dataset is pre converted to 3 X 3 matix
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [52]:
#length of the datasets
x_train.shape  , x_test.shape # we have to make it to 3 X 3
# every image consist of width height and 3 RGB channel


((60000, 28, 28), (10000, 28, 28))

In [53]:
width , height = 28 , 28
input_shape = (width , height , 1)

input_shape

(28, 28, 1)

In [54]:
#reshaping the trainig data
x_train = x_train.reshape(x_train.shape[0] , height , width , 1)
x_test = x_test.reshape(x_test.shape[0] , height , width , 1)

x_train.shape , y_train.shape  #now it is reshaped to 3 X 3
# here the rgb channel is 1 because we are using grey scale(back and white)

((60000, 28, 28, 1), (60000,))

In [55]:
from sklearn.model_selection import train_test_split
x_train , x_val , y_train , y_val = train_test_split(x_train , y_train , test_size = 0.1)

In [56]:
x_train.shape , len(x_train)

((54000, 28, 28, 1), 54000)

In [57]:
#normalize the data
x_train = (x_train - x_train.mean()) / x_train.std()
x_val = (x_val - x_val.mean()) / x_val.std()
x_test = (x_test - x_test.mean()) / x_test.std()
x_train

array([[[[-0.42416471],
         [-0.42416471],
         [-0.42416471],
         ...,
         [-0.42416471],
         [-0.42416471],
         [-0.42416471]],

        [[-0.42416471],
         [-0.42416471],
         [-0.42416471],
         ...,
         [-0.42416471],
         [-0.42416471],
         [-0.42416471]],

        [[-0.42416471],
         [-0.42416471],
         [-0.42416471],
         ...,
         [-0.42416471],
         [-0.42416471],
         [-0.42416471]],

        ...,

        [[-0.42416471],
         [-0.42416471],
         [-0.42416471],
         ...,
         [-0.42416471],
         [-0.42416471],
         [-0.42416471]],

        [[-0.42416471],
         [-0.42416471],
         [-0.42416471],
         ...,
         [-0.42416471],
         [-0.42416471],
         [-0.42416471]],

        [[-0.42416471],
         [-0.42416471],
         [-0.42416471],
         ...,
         [-0.42416471],
         [-0.42416471],
         [-0.42416471]]],


       [[[-0.42416471],


In [58]:
#categorize the data
num_labels = 10 #number of labels

# encoding the labels also
from tensorflow import keras
y_train = keras.utils.to_categorical(y_train)
y_train

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [59]:
y_val = keras.utils.to_categorical(y_val)
y_test = keras.utils.to_categorical(y_test)


##Models

In [60]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense , Dropout , Flatten ,Input , Conv2D , MaxPooling2D , AveragePooling2D

In [61]:
#using traditional lenet 5 architecture
model = Sequential()

#feature extraction block
model.add(Conv2D(6, kernel_size = (5,5) , strides = (1,1), activation = 'tanh' , input_shape = (28,28,1)))
model.add(AveragePooling2D(pool_size = (2,2) , strides = (1 ,1)))
model.add(Conv2D(16, kernel_size = (5,5) , strides = (1,1), activation = 'tanh' )) # 16 represent the number of neurons
model.add(AveragePooling2D(pool_size = (2,2) , strides = (2 ,2)))
model.add(Conv2D(120, kernel_size = (5,5) , strides = (1,1), activation = 'tanh'))
# above is the 5 layers

model.add(Flatten())
model.add(Dense(84, activation = 'tanh'))
model.add(Dense(num_labels , activation = 'softmax'))


In [62]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_5 (Conv2D)           (None, 24, 24, 6)         156       
                                                                 
 average_pooling2d_2 (Avera  (None, 23, 23, 6)         0         
 gePooling2D)                                                    
                                                                 
 conv2d_6 (Conv2D)           (None, 19, 19, 16)        2416      
                                                                 
 average_pooling2d_3 (Avera  (None, 9, 9, 16)          0         
 gePooling2D)                                                    
                                                                 
 conv2d_7 (Conv2D)           (None, 5, 5, 120)         48120     
                                                                 
 flatten_1 (Flatten)         (None, 3000)             

In [63]:
model.compile(loss = keras.losses.categorical_crossentropy , optimizer = 'adam' , metrics = ['accuracy'])

In [65]:
history = model.fit(x_train , y_train , batch_size = 32, epochs = 5 , verbose = 1 , validation_data = (x_val , y_val))  # if we are putting verbos 0 the we will not be able to see the details below

Epoch 1/5
1688/1688 [==============================] - 69s 41ms/step - loss: 0.0629 - accuracy: 0.9808 - val_loss: 0.0723 - val_accuracy: 0.9778
Epoch 2/5
1688/1688 [==============================] - 68s 40ms/step - loss: 0.0572 - accuracy: 0.9825 - val_loss: 0.0720 - val_accuracy: 0.9798
Epoch 3/5
1688/1688 [==============================] - 75s 44ms/step - loss: 0.0608 - accuracy: 0.9817 - val_loss: 0.0711 - val_accuracy: 0.9787
Epoch 4/5
1688/1688 [==============================] - 76s 45ms/step - loss: 0.0535 - accuracy: 0.9837 - val_loss: 0.0588 - val_accuracy: 0.9832
Epoch 5/5
1688/1688 [==============================] - 72s 42ms/step - loss: 0.0486 - accuracy: 0.9849 - val_loss: 0.0758 - val_accuracy: 0.9778


In [70]:
score = model.evaluate(x_test, y_test ,verbose = 1)

313/313 [==============================] - 3s 10ms/step - loss: 0.0590 - accuracy: 0.9798


In [74]:
score[1]*100

97.97999858856201